// Method: GET
GET http://localhost:8000

###
// Method: POST
POST http://localhost:8000
Content-Type: application/json
Accept: application/json

{
  "todo": "Test NodeJS"
}

###
// Method: PUT
PUT http://localhost:8000
Content-Type: application/json
Accept: application/json

{
  "id" : 2,
  "todo" : "Test Ketiga"
}

###
// Method: DELETE
DELETE http://localhost:8000
Content-Type: application/json
Accept: application/json

{
  "id" : 2
}